package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import daoImpl.BitacoraDaoImpl;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private Integer idAcceso;
     private Usuario usuario;
     private Date fechaEntrada;
     private Date fechaSalida;
     private Set bitacoras = new HashSet(0);

    public Acceso() {
    }

    public Acceso(Usuario usuario, Date fechaEntrada, Date fechaSalida, Set bitacoras) {
       this.usuario = usuario;
       this.fechaEntrada = fechaEntrada;
       this.fechaSalida = fechaSalida;
       this.bitacoras = bitacoras;
    }
   
    public Integer getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(Integer idAcceso) {
        this.idAcceso = idAcceso;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }
    public JRDataSource getBitacoraDS(){
        List<Bitacora> b = new ArrayList();
        BitacoraDaoImpl bdi = new BitacoraDaoImpl();
        b = bdi.findByAccess(this);
         return new JRBeanCollectionDataSource(b);
    }



}


