package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA



/**
 * AsignacionSugItem generated by hbm2java
 */
public class AsignacionSugItem  implements java.io.Serializable {


     private int idAsignSug;
     private Sugerencia sugerencia;
     private Item item;

    public AsignacionSugItem() {
    }

	
    public AsignacionSugItem(int idAsignSug) {
        this.idAsignSug = idAsignSug;
    }
    public AsignacionSugItem(int idAsignSug, Sugerencia sugerencia, Item item) {
       this.idAsignSug = idAsignSug;
       this.sugerencia = sugerencia;
       this.item = item;
    }
   
    public int getIdAsignSug() {
        return this.idAsignSug;
    }
    
    public void setIdAsignSug(int idAsignSug) {
        this.idAsignSug = idAsignSug;
    }
    public Sugerencia getSugerencia() {
        return this.sugerencia;
    }
    
    public void setSugerencia(Sugerencia sugerencia) {
        this.sugerencia = sugerencia;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }




}


