package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private Integer idBitacora;
     private Operacion operacion;
     private Acceso acceso;
     private String descripcion;
     private Integer id_elemento;
     private String anterior;
     private String actual;     
     private Date fecha;

    public Bitacora() {
    }

    public Bitacora(Operacion operacion, Acceso acceso,String descripcion,Integer id_elemento,String anterior,String actual, Date fecha) {
       this.operacion = operacion;
       this.acceso = acceso;
       this.descripcion = descripcion;
       this.id_elemento = id_elemento;
       this.anterior = anterior;
       this.actual = actual;
       this.fecha = fecha;
    }
   
    public Integer getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Integer idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Operacion getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Operacion operacion) {
        this.operacion = operacion;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }

    public String getActual() {
        return actual;
    }

    public void setActual(String actual) {
        this.actual = actual;
    }

    public String getAnterior() {
        return anterior;
    }

    public void setAnterior(String anterior) {
        this.anterior = anterior;
    }

    public Integer getId_elemento() {
        return id_elemento;
    }

    public void setId_elemento(Integer id_elemento) {
        this.id_elemento = id_elemento;
    }
    
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


