package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer idContrato;
     private Usuario usuario;
     private Integer estado;
     private Date fechaInicio;
     private Date fechaTermino;
     private Set delegacionIndiUsus = new HashSet(0);
     private Set asignacionCapaContras = new HashSet(0);
     private Set respItems = new HashSet(0);

    public Contrato() {
    }

    public Contrato(Usuario usuario, Integer estado, Date fechaInicio, Date fechaTermino, Set delegacionIndiUsus, Set asignacionCapaContras, Set respItems) {
       this.usuario = usuario;
       this.estado = estado;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.delegacionIndiUsus = delegacionIndiUsus;
       this.asignacionCapaContras = asignacionCapaContras;
       this.respItems = respItems;
    }
   
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public Set getDelegacionIndiUsus() {
        return this.delegacionIndiUsus;
    }
    
    public void setDelegacionIndiUsus(Set delegacionIndiUsus) {
        this.delegacionIndiUsus = delegacionIndiUsus;
    }
    public Set getAsignacionCapaContras() {
        return this.asignacionCapaContras;
    }
    
    public void setAsignacionCapaContras(Set asignacionCapaContras) {
        this.asignacionCapaContras = asignacionCapaContras;
    }
    public Set getRespItems() {
        return this.respItems;
    }
    
    public void setRespItems(Set respItems) {
        this.respItems = respItems;
    }




}


