package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA



/**
 * DelegacionIndiUsu generated by hbm2java
 */
public class DelegacionIndiUsu  implements java.io.Serializable {


     private Integer idDelegacion;
     private Usuario usuario;
     private Indicador indicador;
     private Contrato contrato;

    public DelegacionIndiUsu() {
    }

    public DelegacionIndiUsu(Usuario usuario, Indicador indicador, Contrato contrato) {
       this.usuario = usuario;
       this.indicador = indicador;
       this.contrato = contrato;
    }
   
    public Integer getIdDelegacion() {
        return this.idDelegacion;
    }
    
    public void setIdDelegacion(Integer idDelegacion) {
        this.idDelegacion = idDelegacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }




}


