package pojo;
// Generated Jul 21, 2012 10:46:44 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;


/**
 * EmailInactividad generated by hbm2java
 */
public class EmailInactividad  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private int intentos;
     private Date ultimoAviso;

    public EmailInactividad() {
    }

	
    public EmailInactividad(Usuario usuario, int intentos) {
        this.usuario = usuario;
        this.intentos = intentos;
    }
    public EmailInactividad(Usuario usuario, int intentos, Date ultimoAviso) {
       this.usuario = usuario;
       this.intentos = intentos;
       this.ultimoAviso = ultimoAviso;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getIntentos() {
        return this.intentos;
    }
    
    public void setIntentos(int intentos) {
        this.intentos = intentos;
    }
    public Date getUltimoAviso() {
        return this.ultimoAviso;
    }
    
    public void setUltimoAviso(Date ultimoAviso) {
        this.ultimoAviso = ultimoAviso;
    }




}


