package pojo;
// Generated Nov 14, 2012 4:01:36 PM by Hibernate Tools 3.2.1.GA


/**
 * EmpresaCompleta generated by hbm2java
 */
public class EmpresaCompleta  implements java.io.Serializable {


     private Integer idEmpresaCompleta;
     private Contrato contrato;
     private String razonSocial;
     private String ruc;
     private String correo;
     private String web;
     private Integer anioCreacion;
     private String sector;
     private String nivelEmpresa;
     private String actividadPrimaria;
     private String actividadSecundaria;
     private Integer numeroEmpleadosPermanente;
     private Integer numeroEmpleadosTemp;
     private Integer facturacionAnual;
     private String ofertaPrincipal;
     private String empaqueProducto;
     private String comentariosAnterior;
     private String comentarios;

    public EmpresaCompleta() {
    }

    public EmpresaCompleta(Contrato contrato, String razonSocial, String ruc, String correo, String web, Integer anioCreacion, String sector, String nivelEmpresa, String actividadPrimaria, String actividadSecundaria, Integer numeroEmpleadosPermanente, Integer numeroEmpleadosTemp, Integer facturacionAnual, String ofertaPrincipal, String empaqueProducto, String comentariosAnterior, String comentarios) {
        this.contrato = contrato;
        this.razonSocial = razonSocial;
        this.ruc = ruc;
        this.correo = correo;
        this.web = web;
        this.anioCreacion = anioCreacion;
        this.sector = sector;
        this.nivelEmpresa = nivelEmpresa;
        this.actividadPrimaria = actividadPrimaria;
        this.actividadSecundaria = actividadSecundaria;
        this.numeroEmpleadosPermanente = numeroEmpleadosPermanente;
        this.numeroEmpleadosTemp = numeroEmpleadosTemp;
        this.facturacionAnual = facturacionAnual;
        this.ofertaPrincipal = ofertaPrincipal;
        this.empaqueProducto = empaqueProducto;
        this.comentariosAnterior = comentariosAnterior;
        this.comentarios = comentarios;
    }
    

    public Integer getIdEmpresaCompleta() {
        return this.idEmpresaCompleta;
    }
    
    public void setIdEmpresaCompleta(Integer idEmpresaCompleta) {
        this.idEmpresaCompleta = idEmpresaCompleta;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public Integer getAnioCreacion() {
        return this.anioCreacion;
    }
    
    public void setAnioCreacion(Integer anioCreacion) {
        this.anioCreacion = anioCreacion;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    public String getNivelEmpresa() {
        return this.nivelEmpresa;
    }
    
    public void setNivelEmpresa(String nivelEmpresa) {
        this.nivelEmpresa = nivelEmpresa;
    }
    public String getActividadPrimaria() {
        return this.actividadPrimaria;
    }
    
    public void setActividadPrimaria(String actividadPrimaria) {
        this.actividadPrimaria = actividadPrimaria;
    }
    public String getActividadSecundaria() {
        return this.actividadSecundaria;
    }
    
    public void setActividadSecundaria(String actividadSecundaria) {
        this.actividadSecundaria = actividadSecundaria;
    }
    public Integer getFacturacionAnual() {
        return this.facturacionAnual;
    }
    
    public void setFacturacionAnual(Integer facturacionAnual) {
        this.facturacionAnual = facturacionAnual;
    }
    public String getOfertaPrincipal() {
        return this.ofertaPrincipal;
    }
    
    public void setOfertaPrincipal(String ofertaPrincipal) {
        this.ofertaPrincipal = ofertaPrincipal;
    }
    public String getEmpaqueProducto() {
        return this.empaqueProducto;
    }
    
    public void setEmpaqueProducto(String empaqueProducto) {
        this.empaqueProducto = empaqueProducto;
    }
    public String getComentariosAnterior() {
        return this.comentariosAnterior;
    }
    
    public void setComentariosAnterior(String comentariosAnterior) {
        this.comentariosAnterior = comentariosAnterior;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

    public Integer getNumeroEmpleadosPermanente() {
        return numeroEmpleadosPermanente;
    }

    public void setNumeroEmpleadosPermanente(Integer numeroEmpleadosPermanente) {
        this.numeroEmpleadosPermanente = numeroEmpleadosPermanente;
    }

    public Integer getNumeroEmpleadosTemp() {
        return numeroEmpleadosTemp;
    }

    public void setNumeroEmpleadosTemp(Integer numeroEmpleadosTemp) {
        this.numeroEmpleadosTemp = numeroEmpleadosTemp;
    }




}


