package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA



/**
 * Escala generated by hbm2java
 */
public class Escala  implements java.io.Serializable {


     private Integer idEscala;
     private Variable variable;
     private String descripcion;
     private Integer valoracion;
     private Integer rangoMayor;
     private Integer rangoMenor;

    public Integer getRangoMayor() {
        return rangoMayor;
    }

    public void setRangoMayor(Integer rangoMayor) {
        this.rangoMayor = rangoMayor;
    }

    public Integer getRangoMenor() {
        return rangoMenor;
    }

    public void setRangoMenor(Integer rangoMenor) {
        this.rangoMenor = rangoMenor;
    }

    public Escala() {
    }

    public Escala(Variable variable, String descripcion, Integer valoracion, Integer rangoMayor, Integer rangoMenor) {
       this.variable = variable;
       this.descripcion = descripcion;
       this.valoracion = valoracion;
       this.rangoMayor = rangoMayor;
       this.rangoMenor = rangoMenor;
    }
   
    public Integer getIdEscala() {
        return this.idEscala;
    }
    
    public void setIdEscala(Integer idEscala) {
        this.idEscala = idEscala;
    }
    public Variable getVariable() {
        return this.variable;
    }
    
    public void setVariable(Variable variable) {
        this.variable = variable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(Integer valoracion) {
        this.valoracion = valoracion;
    }




}


