package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Operacion generated by hbm2java
 */
public class Operacion  implements java.io.Serializable {


     private int idOperacion;
     private String nombre;
     private Set bitacoras = new HashSet(0);

    public Operacion() {
    }

	
    public Operacion(int idOperacion) {
        this.idOperacion = idOperacion;
    }
    public Operacion(int idOperacion, String nombre, Set bitacoras) {
       this.idOperacion = idOperacion;
       this.nombre = nombre;
       this.bitacoras = bitacoras;
    }
   
    public int getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(int idOperacion) {
        this.idOperacion = idOperacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getBitacoras() {
        return this.bitacoras;
    }
    
    public void setBitacoras(Set bitacoras) {
        this.bitacoras = bitacoras;
    }




}


