package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private String nombre;
     private String isoCode2;
     private String isoCode3;
     private String direccionFormato;
     private Integer postcodeRequired;
     private Integer status;
     private Set zones = new HashSet(0);

    public Pais() {
    }

    public Pais(String nombre, String isoCode2, String isoCode3, String direccionFormato, Integer postcodeRequired, Integer status, Set zones) {
       this.nombre = nombre;
       this.isoCode2 = isoCode2;
       this.isoCode3 = isoCode3;
       this.direccionFormato = direccionFormato;
       this.postcodeRequired = postcodeRequired;
       this.status = status;
       this.zones = zones;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIsoCode2() {
        return this.isoCode2;
    }
    
    public void setIsoCode2(String isoCode2) {
        this.isoCode2 = isoCode2;
    }
    public String getIsoCode3() {
        return this.isoCode3;
    }
    
    public void setIsoCode3(String isoCode3) {
        this.isoCode3 = isoCode3;
    }
    public String getDireccionFormato() {
        return this.direccionFormato;
    }
    
    public void setDireccionFormato(String direccionFormato) {
        this.direccionFormato = direccionFormato;
    }
    public Integer getPostcodeRequired() {
        return this.postcodeRequired;
    }
    
    public void setPostcodeRequired(Integer postcodeRequired) {
        this.postcodeRequired = postcodeRequired;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getZones() {
        return this.zones;
    }
    
    public void setZones(Set zones) {
        this.zones = zones;
    }




}


