package pojo;
// Generated Nov 14, 2012 4:01:36 PM by Hibernate Tools 3.2.1.GA

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProductos;
     private Empresa empresa;
     private String descripcion;
     private Integer anioIntroduccion;
     private Double porcentajeFacturacion;
     private Double porcentajeExportacion;
     private Integer anioExportacion;

    public Producto() {
    }

    public Producto(Empresa empresa, String descripcion, Integer anioIntroduccion, Double porcentajeFacturacion, Double porcentajeExportacion, Integer anioExportacion) {
       this.empresa = empresa;
       this.descripcion = descripcion;
       this.anioIntroduccion = anioIntroduccion;
       this.porcentajeFacturacion = porcentajeFacturacion;
       this.porcentajeExportacion = porcentajeExportacion;
       this.anioExportacion = anioExportacion;
    }
   
    public Integer getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(Integer idProductos) {
        this.idProductos = idProductos;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getAnioIntroduccion() {
        return this.anioIntroduccion;
    }
    
    public void setAnioIntroduccion(Integer anioIntroduccion) {
        this.anioIntroduccion = anioIntroduccion;
    }
    public Double getPorcentajeFacturacion() {
        return this.porcentajeFacturacion;
    }
    
    public void setPorcentajeFacturacion(Double porcentajeFacturacion) {
        this.porcentajeFacturacion = porcentajeFacturacion;
    }
    public Double getPorcentajeExportacion() {
        return this.porcentajeExportacion;
    }
    
    public void setPorcentajeExportacion(Double porcentajeExportacion) {
        this.porcentajeExportacion = porcentajeExportacion;
    }
    public Integer getAnioExportacion() {
        return this.anioExportacion;
    }
    
    public void setAnioExportacion(Integer anioExportacion) {
        this.anioExportacion = anioExportacion;
    }




}


