package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA



/**
 * RespItem generated by hbm2java
 */
public class RespItem  implements java.io.Serializable {


     private Integer idRepItem;
     private Usuario usuario;
     private Item item;
     private Contrato contrato;
     private Integer resBoolean;
     private String observacion;

    public RespItem() {
    }

    public RespItem(Usuario usuario, Item item, Contrato contrato, Integer resBoolean, String observacion) {
       this.usuario = usuario;
       this.item = item;
       this.contrato = contrato;
       this.resBoolean = resBoolean;
       this.observacion = observacion;
    }
   
    public Integer getIdRepItem() {
        return this.idRepItem;
    }
    
    public void setIdRepItem(Integer idRepItem) {
        this.idRepItem = idRepItem;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Integer getResBoolean() {
        return this.resBoolean;
    }
    
    public void setResBoolean(Integer resBoolean) {
        this.resBoolean = resBoolean;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


