package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sugerencia generated by hbm2java
 */
public class Sugerencia  implements java.io.Serializable {


     private Integer idSugerencia;
     private String descripcion;
     private Set asignacionSugItems = new HashSet(0);
     private Set asignacionSugItems_1 = new HashSet(0);

    public Sugerencia() {
    }

    public Sugerencia(String descripcion, Set asignacionSugItems, Set asignacionSugItems_1) {
       this.descripcion = descripcion;
       this.asignacionSugItems = asignacionSugItems;
       this.asignacionSugItems_1 = asignacionSugItems_1;
    }
   
    public Integer getIdSugerencia() {
        return this.idSugerencia;
    }
    
    public void setIdSugerencia(Integer idSugerencia) {
        this.idSugerencia = idSugerencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAsignacionSugItems() {
        return this.asignacionSugItems;
    }
    
    public void setAsignacionSugItems(Set asignacionSugItems) {
        this.asignacionSugItems = asignacionSugItems;
    }
    public Set getAsignacionSugItems_1() {
        return this.asignacionSugItems_1;
    }
    
    public void setAsignacionSugItems_1(Set asignacionSugItems_1) {
        this.asignacionSugItems_1 = asignacionSugItems_1;
    }




}


