package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import daoImpl.ItemDaoImpl;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 * Variable generated by hbm2java
 */
public class Variable  implements java.io.Serializable {


     private Integer idVariable;
     private Indicador indicador;
     private String nombre;
     private Integer ponderacion;
     private Boolean estado;
     private Set escalas = new HashSet(0);
     private Set items = new HashSet(0);

    public Variable() {
    }

    public Variable(Indicador indicador, String nombre, Integer ponderacion, Boolean estado, Set escalas, Set items) {
       this.indicador = indicador;
       this.nombre = nombre;
       this.ponderacion = ponderacion;
       this.estado = estado;
       this.escalas = escalas;
       this.items = items;
    }
   
    public Integer getIdVariable() {
        return this.idVariable;
    }
    
    public void setIdVariable(Integer idVariable) {
        this.idVariable = idVariable;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(Integer ponderacion) {
        this.ponderacion = ponderacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getEscalas() {
        return this.escalas;
    }
    
    public void setEscalas(Set escalas) {
        this.escalas = escalas;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

   public JRDataSource getItemDS(){
        List<Item> listitems = new ArrayList<Item>();
        ItemDaoImpl idi = new ItemDaoImpl();
        listitems = idi.findByVariable(this);
         return new JRBeanCollectionDataSource(listitems);
    }


}


