package pojo;
// Generated Nov 3, 2011 11:28:07 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private Integer idZone;
     private Pais pais;
     private String code;
     private String nombre;
     private Integer status;
     private Set empresas = new HashSet(0);

    public Zone() {
    }

    public Zone(Pais pais, String code, String nombre, Integer status, Set empresas) {
       this.pais = pais;
       this.code = code;
       this.nombre = nombre;
       this.status = status;
       this.empresas = empresas;
    }
   
    public Integer getIdZone() {
        return this.idZone;
    }
    
    public void setIdZone(Integer idZone) {
        this.idZone = idZone;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


